[2021-03-23 15:27:33,139] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: data_prep_and_process.data_preperation 2021-03-23T09:57:15.116028+00:00 [queued]>
[2021-03-23 15:27:33,150] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: data_prep_and_process.data_preperation 2021-03-23T09:57:15.116028+00:00 [queued]>
[2021-03-23 15:27:33,151] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 15:27:33,151] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-03-23 15:27:33,151] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 15:27:33,161] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): data_preperation> on 2021-03-23T09:57:15.116028+00:00
[2021-03-23 15:27:33,165] {standard_task_runner.py:52} INFO - Started process 42411 to run task
[2021-03-23 15:27:33,176] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'data_prep_and_process', 'data_preperation', '2021-03-23T09:57:15.116028+00:00', '--job-id', '35', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/master_dag.py', '--cfg-path', '/var/folders/yw/952dv3rd0332_2c7vqyq34vc0000gp/T/tmpkymc6858', '--error-file', '/var/folders/yw/952dv3rd0332_2c7vqyq34vc0000gp/T/tmppia26c9v']
[2021-03-23 15:27:33,182] {standard_task_runner.py:77} INFO - Job 35: Subtask data_preperation
[2021-03-23 15:27:38,229] {logging_mixin.py:104} INFO - Running <TaskInstance: data_prep_and_process.data_preperation 2021-03-23T09:57:15.116028+00:00 [running]> on host FACT-LAP-135.local
[2021-03-23 15:27:43,280] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=skadhithya95@example.com
AIRFLOW_CTX_DAG_OWNER=adhithya
AIRFLOW_CTX_DAG_ID=data_prep_and_process
AIRFLOW_CTX_TASK_ID=data_preperation
AIRFLOW_CTX_EXECUTION_DATE=2021-03-23T09:57:15.116028+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-23T09:57:15.116028+00:00
[2021-03-23 15:27:43,284] {data_preparation.py:54} INFO - URL to fetch records --> https://api.exchangeratesapi.io/history?start_at=2018-01-01&end_at=2021-03-23

[2021-03-23 15:27:43,285] {data_preparation.py:57} INFO - Get request --> hitting the URL to fetch data
[2021-03-23 15:27:43,587] {data_preparation.py:59} INFO - Get request ::: Status --> Successful

[2021-03-23 15:27:43,597] {data_preparation.py:66} INFO - Display sample records fetched from URL

[2021-03-23 15:27:43,598] {logging_mixin.py:104} INFO - {'CAD': 1.5466, 'HKD': 9.0327, 'ISK': 163.5, 'PHP': 56.407, 'DKK': 7.4455, 'HUF': 366.24, 'CZK': 27.131, 'AUD': 1.6533, 'RON': 4.8674, 'SEK': 10.3625, 'IDR': 17064.82, 'INR': 86.7555, 'BRL': 6.6916, 'RUB': 93.745, 'HRK': 7.5695, 'JPY': 121.93, 'THB': 36.249, 'CHF': 1.0695, 'SGD': 1.5903, 'PLN': 4.6018, 'BGN': 1.9558, 'TRY': 9.8332, 'CNY': 7.7962, 'NOK': 11.1128, 'NZD': 1.7565, 'ZAR': 18.8972, 'USD': 1.1652, 'MXN': 24.7327, 'ILS': 3.9681, 'GBP': 0.90053, 'KRW': 1320.61, 'MYR': 4.8443}
[2021-03-23 15:27:43,599] {logging_mixin.py:104} INFO - 
[2021-03-23 15:27:43,707] {data_preparation.py:143} INFO - Pushing JSON file to Local drive - Path ::: /Users/adhithyakarthikeyan/currency_hist_records.json

[2021-03-23 15:27:43,888] {data_preparation.py:147} INFO - Status ::: Succcessful --> Currency historical records Path ::: /Users/adhithyakarthikeyan/currency_hist_records.json

[2021-03-23 15:27:43,892] {data_preparation.py:180} INFO - Filtering historical data for currencies
[2021-03-23 15:27:43,892] {data_preparation.py:190} INFO - required_currencies['EUR', 'USD', 'JPY', 'CAD', 'GBP', 'NZD', 'INR']
[2021-03-23 15:27:43,898] {python.py:118} INFO - Done. Returned value was: <data_preparation.data_preparation object at 0x7fc0cb980af0>
[2021-03-23 15:27:43,899] {xcom.py:237} ERROR - Could not serialize the XCom value into JSON. If you are using pickles instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config.
[2021-03-23 15:27:43,900] {taskinstance.py:1455} ERROR - Object of type data_preparation is not JSON serializable
Traceback (most recent call last):
  File "/Users/adhithyakarthikeyan/opt/anaconda3/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/adhithyakarthikeyan/opt/anaconda3/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/adhithyakarthikeyan/opt/anaconda3/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1318, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/Users/adhithyakarthikeyan/opt/anaconda3/lib/python3.8/site-packages/airflow/utils/session.py", line 65, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/adhithyakarthikeyan/opt/anaconda3/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1893, in xcom_push
    XCom.set(
  File "/Users/adhithyakarthikeyan/opt/anaconda3/lib/python3.8/site-packages/airflow/utils/session.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/Users/adhithyakarthikeyan/opt/anaconda3/lib/python3.8/site-packages/airflow/models/xcom.py", line 88, in set
    value = XCom.serialize_value(value)
  File "/Users/adhithyakarthikeyan/opt/anaconda3/lib/python3.8/site-packages/airflow/models/xcom.py", line 235, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/Users/adhithyakarthikeyan/opt/anaconda3/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Users/adhithyakarthikeyan/opt/anaconda3/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/adhithyakarthikeyan/opt/anaconda3/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/adhithyakarthikeyan/opt/anaconda3/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type data_preparation is not JSON serializable
[2021-03-23 15:27:43,903] {taskinstance.py:1496} INFO - Marking task as UP_FOR_RETRY. dag_id=data_prep_and_process, task_id=data_preperation, execution_date=20210323T095715, start_date=20210323T095733, end_date=20210323T095743
[2021-03-23 15:27:43,944] {local_task_job.py:146} INFO - Task exited with return code 1
